trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildImage
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.Repository.Name):$(Build.BuildId)

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployToAzure
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              appType: 'webAppLinux'
              DockerNamespace: '<yourDockerHubNamespace>'
              DockerRepository: '<yourRepositoryName>'
              DockerImageTag: '$(Build.BuildId)'
