trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildImage
        steps:
          - script: echo "Building Docker Image..."
            displayName: 'Build Docker Image'
          - task: Docker@2
            inputs:
              command: build
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.Repository.Name):$(Build.BuildId)

  - stage: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master' ))
    jobs:
      - deployment: DeployToAzure
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to Azure App Service..."
                  displayName: 'Deploy to Azure'
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
                    appType: 'webAppLinux'
                    WebAppName: '<beStrongAppService>'
                    package: '**/*.zip'