# trigger:
# - main
variables:
  -group: Terraform
pool:
  vmImage: ubuntu-latest
stages:  
- stage: BuildInfrastructure
  displayName: Build infrastructure
  jobs:
  - job: Terraform
    displayName: Terraform Apply
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
      
    - task: TerraformTaskV4@4
      displayName: 'Init Terraform'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
        backendAzureRmResourceGroupName: 'tfstate'
        backendAzureRmStorageAccountName: 'tfstatedocker123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      
    - task: TerraformTaskV4@4
      displayName: 'Validate Terraform'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

    - task: TerraformTaskV4@4
      displayName: 'Plan Terraform'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: >- 
                        
                        -var "subscription_id=$(subscription_id)"
                        -var "client_id=$(client_id)"
                        -var "client_secret=$(client_secret)"
                        -var "tenant_id=$(tenant_id)"

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: >- 
                        -auto-approve
                        -var "subscription_id=$(subscription_id)"
                        -var "client_id=$(client_id)"
                        -var "client_secret=$(client_secret)"
                        -var "tenant_id=$(tenant_id)"


